defmodule Kanban.Tasks.CompletionValidationExportsTest do
  @moduledoc """
  Drift guard for the public API surface of `Kanban.Tasks.CompletionValidation`
  (W1953).

  The module was split into six focused siblings, with the moved
  implementations reached by `defdelegate`. Thirteen lib/ modules and six test
  files call this module by name, so the parent must keep exporting every
  function it exported before the split, at the same arity — a delegate that is
  dropped or renamed is a silent breaking change for every caller.

  This lives in its own file rather than in `completion_validation_test.exs`
  because that file is the primary evidence that the split moved no behaviour,
  and it is deliberately kept byte-unchanged.
  """
  use ExUnit.Case, async: true

  alias Kanban.Tasks.CompletionValidation

  # The exact name/arity set exported before the split (commit 46cde432),
  # including the arities generated by default arguments.
  @exports [
    {:acceptance_criteria_count_failures, 2},
    {:behaviour_test_statuses, 0},
    {:considerations_status_consistency_failures, 1},
    {:coverage_shortfall, 2},
    {:cross_check_reviewer_result, 2},
    {:issue_categories, 0},
    {:project_checklist_count, 0},
    {:required_review_sections, 0},
    {:review_contract_failures, 1},
    {:review_contract_failures, 2},
    {:skip_reasons, 0},
    {:validate_changed_files, 1},
    {:validate_explorer_result, 1},
    {:validate_reviewer_result, 1},
    {:validate_reviewer_result, 2}
  ]

  describe "public API surface" do
    test "every pre-split export is still callable on the parent at the same arity" do
      exported = CompletionValidation.__info__(:functions) |> MapSet.new()

      missing = Enum.reject(@exports, &MapSet.member?(exported, &1))

      assert missing == [],
             "the parent stopped exporting: #{inspect(missing)} — every caller of those names breaks"
    end

    test "the accessors still return their documented shapes" do
      assert is_list(CompletionValidation.skip_reasons())
      assert Enum.all?(CompletionValidation.skip_reasons(), &is_atom/1)

      assert is_list(CompletionValidation.required_review_sections())
      assert :project_checks in CompletionValidation.required_review_sections()

      assert is_list(CompletionValidation.issue_categories())
      assert Enum.all?(CompletionValidation.issue_categories(), &is_atom/1)

      assert CompletionValidation.behaviour_test_statuses() ==
               [:planned, :passing, :failing, :not_applicable]

      count = CompletionValidation.project_checklist_count()
      assert is_integer(count) and count > 0
    end

    test "each delegated function returns exactly what its sibling returns" do
      # A delegate that pointed at the wrong module or the wrong function would
      # still compile; this pins that the parent and the sibling agree.
      alias Kanban.Tasks.CompletionValidation.AcceptanceCounts
      alias Kanban.Tasks.CompletionValidation.BehaviourTestMatrix
      alias Kanban.Tasks.CompletionValidation.ChangedFiles
      alias Kanban.Tasks.CompletionValidation.ReviewContract

      assert CompletionValidation.behaviour_test_statuses() == BehaviourTestMatrix.statuses()
      assert CompletionValidation.required_review_sections() == ReviewContract.sections()
      assert CompletionValidation.project_checklist_count() == ReviewContract.checklist_count()

      assert CompletionValidation.coverage_shortfall(25, 3) ==
               ReviewContract.coverage_shortfall(25, 3)

      review = %{"dispatched" => true}

      assert CompletionValidation.review_contract_failures(review) ==
               ReviewContract.failures(review)

      task = %{acceptance_criteria: "one\ntwo"}

      assert CompletionValidation.acceptance_criteria_count_failures(review, task) ==
               AcceptanceCounts.failures(review, task)

      files = [%{"path" => "../x"}]
      assert CompletionValidation.validate_changed_files(files) == ChangedFiles.validate(files)
    end
  end
end
