defmodule KanbanWeb.WorkspaceMetricsPdfHTMLTest do
  @moduledoc """
  Unit tests for the workspace metrics PDF body.

  Every test calls the template and geometry functions DIRECTLY — no
  connection, no database, no headless browser. The chart math lives in named
  module functions precisely so the degenerate cases (empty, single-point,
  all-zero) can be asserted here rather than only observed through a rendered
  PDF.
  """

  use ExUnit.Case, async: true

  alias Kanban.Metrics.Workspace
  alias KanbanWeb.WorkspaceMetricsPdfHTML

  @module_path "lib/kanban_web/controllers/workspace_metrics_pdf_html.ex"

  defp render_to_string(rendered) do
    rendered
    |> Phoenix.HTML.Safe.to_iodata()
    |> IO.iodata_to_binary()
  end

  defp series(minutes_list) do
    minutes_list
    |> Enum.with_index()
    |> Enum.map(fn {minutes, index} ->
      %{date: Date.add(~D[2026-07-01], index), minutes: minutes}
    end)
  end

  defp overview(attrs \\ %{}) do
    Map.merge(
      %{
        kpis: %{
          cycle_time_median_minutes: 161,
          cycle_time_delta_pct: -12.5,
          lead_time_p50_minutes: 2880,
          lead_time_delta_pct: 4.0,
          throughput_per_day: 3.25,
          throughput_delta_pct: 10.0,
          review_wait_minutes: 45,
          review_wait_delta_pct: 0.0
        },
        cycle_series: series([30, 60, 90]),
        lead_series: series([120, 240, 360]),
        throughput_series: [1, 4, 2],
        leaderboard: [
          %{name: "Claude Opus 4.8", kind: :agent, completed: 12, success_pct: 91.6}
        ],
        flow_snapshots: [
          %{date: ~D[2026-07-01], backlog: 5, ready: 3, doing: 2, review: 1, done: 8},
          %{date: ~D[2026-07-02], backlog: 4, ready: 4, doing: 3, review: 2, done: 11}
        ]
      },
      attrs
    )
  end

  defp assigns(attrs) do
    Map.merge(
      %{
        overview: overview(),
        window_days: 14,
        timezone: "Etc/UTC",
        exclude_weekends: false,
        generated_at: ~U[2026-07-19 12:00:00Z],
        board_ids: nil
      },
      attrs
    )
  end

  defp render(attrs \\ %{}) do
    attrs |> assigns() |> WorkspaceMetricsPdfHTML.report() |> render_to_string()
  end

  describe "report/1 — document structure" do
    test "renders every section of the workspace metrics page, including the lead time chart" do
      html = render()

      assert html =~ "Cycle time · median"
      assert html =~ "Lead time · median"
      assert html =~ "Wait time · Review"
      assert html =~ "Cycle time · daily median (min)"
      assert html =~ "Lead time · daily median (min)"
      assert html =~ "Throughput · tasks completed per day"
      assert html =~ "Agents · last"
      assert html =~ "Cumulative flow"
    end

    test "the lead time chart is rendered as a distinct series, not a duplicate of cycle" do
      html = render()

      # Distinct markers and a distinct stroke are what separate the two charts
      # in print; without both, the second chart reads as a repeat of the first.
      assert html =~ "cycle-time-point-0"
      assert html =~ "lead-time-point-0"
      assert html =~ "#f59e0b"
      assert html =~ "#8b5cf6"
    end

    test "emits a standalone document with its styling injected inline" do
      html = render()

      assert html =~ "<!DOCTYPE html>"
      assert html =~ "<style>"
      # Asserts the @page footer DECLARATION is present, mirroring the board
      # PDF. It does not prove a rendered footer: ChromicPDF drives Chrome's
      # Page.printToPDF, which does not implement CSS paged-media margin boxes.
      assert html =~ "Generated by Stride"
      # A PDF has no asset pipeline behind it — nothing may be linked out.
      refute html =~ "<link"
    end

    test "contains no script element, keeping the renderer surface inert" do
      html = render()

      refute html =~ "<script"
      refute html =~ "<canvas"
    end

    test "renders charts as inline vector graphics" do
      html = render()

      assert html =~ "<svg"
      assert html =~ "<polyline"
      assert html =~ "<rect"
      assert html =~ "<polygon"
    end

    test "renders no theme token in the OUTPUT" do
      # The policy test greps the source; this asserts the rendered document,
      # which is what actually reaches the renderer.
      refute render() =~ "var(--"
    end
  end

  describe "report/1 — applied filters" do
    test "reports the window" do
      assert render(%{window_days: 30}) =~ "30"
    end

    test "reports all boards when no subset was selected" do
      assert render(%{board_ids: nil}) =~ "All boards"
    end

    test "reports a single selected board" do
      assert render(%{board_ids: [7]}) =~ "1 board"
    end

    test "reports a multi-board selection by count" do
      assert render(%{board_ids: [7, 9]}) =~ "2 boards"
    end

    test "reports an all-forged selection as zero boards" do
      # [] means every requested board id was dropped as forged — a zero
      # report, and the document should say so rather than implying all boards.
      assert render(%{board_ids: []}) =~ "0 boards"
    end

    test "anchors the printed window range on the report's timezone, not UTC" do
      # At 12:00 UTC on Jul 19 it is already Jul 20 02:00 in Kiritimati (+14)
      # but still Jul 19 01:00 in Midway (-11). Anchoring on Date.utc_today/0
      # would print the same range for both while the charts bucket by local day.
      at = ~U[2026-07-19 12:00:00Z]

      ahead = render(%{generated_at: at, timezone: "Pacific/Kiritimati", window_days: 7})
      behind = render(%{generated_at: at, timezone: "Pacific/Midway", window_days: 7})

      refute ahead == behind
      assert ahead =~ "Jul 20"
      assert behind =~ "Jul 19"
    end

    test "falls back to the raw timestamp when the zone cannot be resolved" do
      html = render(%{generated_at: ~U[2026-07-19 09:00:00Z], timezone: "Not/AZone"})

      assert html =~ "Jul 19"
    end

    test "reports the timezone and the weekend filter" do
      html = render(%{timezone: "America/Toronto", exclude_weekends: true})

      assert html =~ "America/Toronto"
      assert html =~ "Exclude Weekends"
    end

    test "never renders a board name, because it never resolves boards" do
      source = File.read!(@module_path)
      [_moduledoc, code] = String.split(source, ~s(  use KanbanWeb, :html), parts: 2)

      refute code =~ "Boards.list_boards"
      refute code =~ "alias Kanban.Boards"
    end
  end

  describe "line_chart_geometry/3 — degenerate inputs" do
    test "an empty series produces no points and does not raise" do
      geometry = WorkspaceMetricsPdfHTML.line_chart_geometry([])

      assert geometry.points == []
      assert geometry.polyline == ""
      assert geometry.area == ""
      assert geometry.max > 0
    end

    test "a single data point is centred horizontally" do
      geometry = series([42]) |> WorkspaceMetricsPdfHTML.line_chart_geometry()

      assert [%{x: x}] = geometry.points
      assert x == WorkspaceMetricsPdfHTML.chart_width() / 2
    end

    test "an all-zero series yields a non-zero scale maximum" do
      # This is the divide-by-zero criterion asserted directly: every y
      # projection divides by this maximum.
      geometry = series([0, 0, 0]) |> WorkspaceMetricsPdfHTML.line_chart_geometry()

      assert geometry.max > 0
      assert length(geometry.points) == 3
      assert Enum.all?(geometry.points, &(&1.y == WorkspaceMetricsPdfHTML.chart_height() / 1))
    end

    test "a very large peak still produces a bounded set of ticks" do
      geometry = series([98_765]) |> WorkspaceMetricsPdfHTML.line_chart_geometry()

      assert geometry.max >= 98_765
      assert length(geometry.ticks) <= 8
    end

    test "the area polygon is omitted for fewer than two points" do
      single = series([5]) |> WorkspaceMetricsPdfHTML.line_chart_geometry()
      pair = series([5, 6]) |> WorkspaceMetricsPdfHTML.line_chart_geometry()

      assert single.area == ""
      assert pair.area != ""
    end
  end

  describe "bar_chart_geometry/4" do
    test "an empty count series produces no bars and does not raise" do
      geometry = WorkspaceMetricsPdfHTML.bar_chart_geometry([], [])

      assert geometry.bars == []
      assert geometry.max > 0
    end

    test "an all-zero count series renders zero-height bars without dividing by zero" do
      geometry =
        WorkspaceMetricsPdfHTML.bar_chart_geometry([0, 0], [~D[2026-07-01], ~D[2026-07-02]])

      assert length(geometry.bars) == 2
      assert Enum.all?(geometry.bars, &(&1.height == 0.0))
    end

    test "bars carry the supplied dates rather than inferring them" do
      dates = [~D[2026-07-01], ~D[2026-07-06]]
      geometry = WorkspaceMetricsPdfHTML.bar_chart_geometry([2, 5], dates)

      assert Enum.map(geometry.bars, & &1.date) == dates
    end
  end

  describe "flow_chart_geometry/3" do
    test "no snapshots produces no layers and a clamped peak" do
      geometry = WorkspaceMetricsPdfHTML.flow_chart_geometry([])

      assert geometry.layers == []
      assert geometry.peak == 1
    end

    test "an all-zero snapshot set clamps the peak to one rather than dividing by zero" do
      snapshots = [%{date: ~D[2026-07-01], backlog: 0, ready: 0, doing: 0, review: 0, done: 0}]

      assert WorkspaceMetricsPdfHTML.flow_chart_geometry(snapshots).peak == 1
    end

    test "stacks one polygon per column" do
      geometry = WorkspaceMetricsPdfHTML.flow_chart_geometry(overview().flow_snapshots)

      assert length(geometry.layers) == 5
      assert Enum.all?(geometry.layers, &(&1.points != ""))
    end
  end

  describe "x_axis_labels/2" do
    test "handles an empty and a single-date series without dividing by zero" do
      assert WorkspaceMetricsPdfHTML.x_axis_labels([]) == []
      assert [%{index: 0}] = WorkspaceMetricsPdfHTML.x_axis_labels([~D[2026-07-01]])
    end

    test "thins a 90-day window to at most eight labels" do
      dates = Enum.map(0..89, &Date.add(~D[2026-01-01], &1))

      assert length(WorkspaceMetricsPdfHTML.x_axis_labels(dates)) <= 8
    end

    test "honours the bound at every window length, including the 14-day default" do
      # A flooring stride let 9-14 entries through at stride 1, emitting every
      # label — the default window was the worst case and was unguarded.
      for count <- 1..90 do
        dates = Enum.map(0..(count - 1), &Date.add(~D[2026-01-01], &1))
        labels = WorkspaceMetricsPdfHTML.x_axis_labels(dates)

        assert length(labels) <= 8, "#{count} dates produced #{length(labels)} labels"
      end
    end

    test "always labels the final date so the chart's right edge is not blank" do
      for count <- [2, 13, 14, 30, 90] do
        dates = Enum.map(0..(count - 1), &Date.add(~D[2026-01-01], &1))
        labels = WorkspaceMetricsPdfHTML.x_axis_labels(dates)

        assert List.last(labels).index == count - 1, "#{count} dates lost its last label"
      end
    end
  end

  describe "bar_label_x/2" do
    test "centres a label on its band rather than on the line-chart point scale" do
      # Bars are laid out on a band scale; reusing label_x/2 offset every label
      # by half a slot and pushed the last one past the final bar.
      width = WorkspaceMetricsPdfHTML.chart_width()

      assert WorkspaceMetricsPdfHTML.bar_label_x(0, 10) == width / 10 * 0.5
      assert WorkspaceMetricsPdfHTML.bar_label_x(9, 10) < width
      assert WorkspaceMetricsPdfHTML.bar_label_x(0, 0) == width / 2
    end
  end

  describe "empty workspace" do
    test "renders the real zero shape without raising" do
      # placeholder_overview/1 is the exact shape an empty workspace produces:
      # window-sized zero-filled series, all-zero KPIs, and an EMPTY leaderboard.
      zero = Workspace.placeholder_overview(window_days: 14, timezone: "Etc/UTC")
      html = render(%{overview: zero})

      assert html =~ "Metrics"
      assert html =~ "Cumulative flow"
    end

    test "an empty leaderboard renders the no-completions message, not an empty table" do
      html = render(%{overview: overview(%{leaderboard: []})})

      assert html =~ "No completions in the last"
      # The class name also appears in the stylesheet, so assert on the ELEMENT:
      # an empty leaderboard must render the message instead of an empty table.
      refute html =~ "<table"
    end
  end

  describe "escaping" do
    test "escapes markup characters in an agent name" do
      hostile = ~s|<script>alert("x")</script>|

      html =
        render(%{
          overview:
            overview(%{
              leaderboard: [%{name: hostile, kind: :agent, completed: 3, success_pct: 66.6}]
            })
        })

      assert html =~ "&lt;script&gt;"
      refute html =~ "<script>alert"
    end

    test "the module performs exactly one raw injection, the stylesheet" do
      template =
        File.read!("lib/kanban_web/controllers/workspace_metrics_pdf_html/report.html.heex")

      assert template |> String.split("Phoenix.HTML.raw(") |> length() == 2
      assert template =~ ~s|Phoenix.HTML.raw("<style>" <> pdf_css() <> "</style>")|
    end
  end

  describe "translation" do
    setup do
      on_exit(fn -> Gettext.put_locale(KanbanWeb.Gettext, "en") end)
      :ok
    end

    test "renders visible strings through translation in a translated locale" do
      Gettext.put_locale(KanbanWeb.Gettext, "ja")
      html = render()

      # The Japanese catalog translates this section heading; if the template
      # had hardcoded English (as the board PDF does), this would fail.
      refute html =~ "Cumulative flow"
    end

    test "declares the active locale on the document" do
      Gettext.put_locale(KanbanWeb.Gettext, "ja")

      assert render() =~ ~s(<html lang="ja">)
    end

    test "falls back to the source string in an untranslated locale" do
      Gettext.put_locale(KanbanWeb.Gettext, "en")

      assert render() =~ "Cumulative flow"
    end
  end

  describe "formatting" do
    test "minute values use the same formatter as the on-screen KPI strip" do
      html = render()

      # 161 minutes reads as 2h 41m on the page; a cruder formatter would
      # render "161m" here and the export would disagree with the screen.
      assert html =~ "2h 41m"
    end

    test "throughput keeps two decimals and is not run through the minute formatter" do
      assert render() =~ "3.25"
    end
  end
end
