import Config

# Configure your database
config :kanban, Kanban.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "kanban_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# D115: the dev signing-key placeholder must FAIL CLOSED for a running server.
# Non-server Mix tasks (mix help, deps.audit, compile, …) still load with the
# clearly-labeled placeholder, but starting the dev endpoint (`mix phx.server`,
# `iex -S mix phx.server`, or PHX_SERVER=1) without exporting SECRET_KEY_BASE now
# raises instead of silently serving with a publicly-known key — closing the
# forge-any-session risk if such a server is ever exposed via tunneling.
dev_server_starting? =
  System.get_env("PHX_SERVER") != nil or "phx.server" in System.argv()

dev_secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    if dev_server_starting? do
      raise """
      SECRET_KEY_BASE is not set. Export a per-developer key before starting the dev server:

          export SECRET_KEY_BASE="$(mix phx.gen.secret)"

      The dev placeholder key is only for non-server Mix tasks; a server using it is
      unsafe if ever exposed via tunneling or port forwarding.
      """
    else
      "DEV_PLACEHOLDER_KEY_NOT_FOR_PUBLIC_USE_RUN_mix_phx_gen_secret_AND_EXPORT_SECRET_KEY_BASE_xxxxx"
    end

config :kanban, KanbanWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # Per-developer dev signing key (see the D115 block above). Each contributor
  # SHOULD export SECRET_KEY_BASE (generate one with `mix phx.gen.secret`).
  secret_key_base: dev_secret_key_base,
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:kanban, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:kanban, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :kanban, KanbanWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/kanban_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :kanban, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
