defmodule KanbanWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :kanban

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # `secure` marks the session cookie Secure so it is never sent over plaintext
  # HTTP. It is gated on config (default false) so it is on in production and
  # off in dev/test, where the server runs over http and a Secure cookie would
  # be dropped by the browser (D158). HSTS + http→https redirect are handled by
  # `force_ssl` in config/prod.exs.
  @session_options [
    store: :cookie,
    key: "_kanban_key",
    signing_salt: "MkVVRya+",
    same_site: "Lax",
    secure: Application.compile_env(:kanban, :session_cookie_secure, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options, user_agent: true, peer_data: true]],
    longpoll: [connect_info: [session: @session_options, user_agent: true, peer_data: true]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :kanban,
    gzip: not code_reloading?,
    only: KanbanWeb.static_paths()

  # Tidewave for development
  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :kanban
  end

  # Lets LiveView processes spawned during tests share the test
  # owner's Ecto sandbox connection, avoiding the noisy
  # "Postgrex.Protocol disconnected" log when a LiveView checks out
  # its own connection and exits with the test.
  if Application.compile_env(:kanban, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox, repo: Kanban.Repo
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Plug.Parsers, wrapped so a parse failure on an /api path (a malformed
  # query string or body, an oversized body) renders as JSON rather than
  # HTML (D353). It must be the first plug that parses the query string:
  # an earlier plug that calls fetch_query_params would raise the 400 outside
  # the wrapper, and the /api client would get an HTML error page.
  plug KanbanWeb.Plugs.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  # Placed after the parsers (D353) because it calls fetch_query_params; see
  # the note above. Dev-tool trade-off: its Logger metadata is now set after
  # Plug.Telemetry's request-start log line and after parsing, so the
  # LiveDashboard request-logger stream no longer shows the "GET /path" line
  # or anything logged while parsing. The rest of the request is captured.
  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug KanbanWeb.Router
end
