defmodule Kanban.Tasks.GoalPlacement do
  @moduledoc """
  Places a goal in the column its child tasks have moved to.

  Extracted from `Kanban.Tasks.Goals` (D357) to keep that module under the
  size cap. `Kanban.Tasks.Goals.update_parent_goal_position/4` decides
  *whether* and *where* a goal moves; this module performs the move.

  The bulk writes here bypass Ecto's autogenerated timestamps, so each one
  sets `updated_at` explicitly — see `Kanban.Tasks.Positioning`.
  """

  import Ecto.Query, warn: false

  alias Kanban.Notifications.Events
  alias Kanban.Repo
  alias Kanban.Tasks.Broadcaster
  alias Kanban.Tasks.Queries
  alias Kanban.Tasks.Task

  require Logger

  defp calculate_goal_target_position(min_child_position, last_goal_position) do
    cond do
      min_child_position != nil && last_goal_position != nil ->
        min(min_child_position, last_goal_position + 1)

      min_child_position != nil ->
        min_child_position

      last_goal_position != nil ->
        last_goal_position + 1

      true ->
        0
    end
  end

  # Position queries below exclude archived tasks (is_nil(archived_at)) so the
  # goal reposition only considers and shifts live cards — archived rows keep
  # their stale positions and are never renumbered.
  defp min_live_child_position(column_id, goal_id) do
    from(t in Task,
      where: t.column_id == ^column_id and t.parent_id == ^goal_id and is_nil(t.archived_at),
      select: min(t.position)
    )
    |> Repo.one()
  end

  defp max_other_live_goal_position(column_id, goal_id) do
    from(t in Task,
      where:
        t.column_id == ^column_id and t.type == :goal and t.id != ^goal_id and
          is_nil(t.archived_at),
      select: max(t.position)
    )
    |> Repo.one()
  end

  defp live_tasks_to_shift(column_id, target_position, goal_id) do
    from(t in Task,
      where:
        t.column_id == ^column_id and t.position >= ^target_position and t.id != ^goal_id and
          is_nil(t.archived_at),
      select: %{id: t.id, position: t.position},
      order_by: [desc: t.position]
    )
    |> Repo.all()
  end

  @doc """
  Moves `parent_goal` into `target_column`, placing it after the column's
  other live goals and no lower than its first live child, and shifts the
  live tasks at or below that position down by one.

  `now` is the whole-second UTC `updated_at` stamped on the goal and on every
  shifted task (D357). Runs inside the caller's transaction.
  """
  def move_goal_to_top_with_other_goals(parent_goal, target_column, now) do
    min_child_position = min_live_child_position(target_column.id, parent_goal.id)
    last_goal_position = max_other_live_goal_position(target_column.id, parent_goal.id)

    target_position = calculate_goal_target_position(min_child_position, last_goal_position)

    Logger.info(
      "Moving goal #{parent_goal.identifier} to column #{target_column.id} at position #{target_position} (min_child_position: #{inspect(min_child_position)}, last_goal_position: #{inspect(last_goal_position)})"
    )

    Task
    |> where([t], t.id == ^parent_goal.id)
    |> Repo.update_all(set: [column_id: target_column.id, position: -999_999])

    tasks_to_shift = live_tasks_to_shift(target_column.id, target_position, parent_goal.id)

    Logger.info("Shifting #{length(tasks_to_shift)} tasks from position #{target_position}")

    Enum.each(tasks_to_shift, fn task ->
      Task
      |> where([t], t.id == ^task.id)
      |> Repo.update_all(set: [position: task.position + 1, updated_at: now])
    end)

    is_done = String.downcase(target_column.name) == "done"

    updates =
      if is_done do
        [
          position: target_position,
          completed_at: DateTime.utc_now(),
          status: :completed,
          updated_at: now
        ]
      else
        [position: target_position, completed_at: nil, status: :open, updated_at: now]
      end

    Task
    |> where([t], t.id == ^parent_goal.id)
    |> Repo.update_all(set: updates)

    Logger.info("Goal #{parent_goal.identifier} placed at position #{target_position}")

    updated_goal = Queries.get_task!(parent_goal.id)
    # This runs inside the caller's transaction, so no webhook is queued here
    # (the moving task emits its own event after commit) and the notification
    # is deferred.
    Broadcaster.broadcast_task_change(updated_goal, :task_moved, webhook: false)
    Events.goal_completed_after_commit(updated_goal)
    {:ok, :moved}
  end
end
