defmodule Kanban.Tasks.Positioning do
  @moduledoc """
  Task positioning and movement within and between columns.

  Handles moving tasks, reordering, WIP limit checks, and position-related
  helpers used by other submodules.

  ## `updated_at` on bulk writes (D357)

  Moves and reorders write rows with `Repo.update_all/2`, which bypasses
  Ecto's autogenerated timestamps, so every *final* write here sets
  `updated_at` explicitly. Each operation captures one whole-second UTC value
  (`DateTime.utc_now(:second)`) and stamps every row it changes with it, so
  `GET /api/tasks?updated_since=` sees the move.

  Siblings whose position is reshuffled to make room or close a gap are
  bumped too: `position` is part of the client-visible task object, so a
  synced mirror would otherwise keep stale ordering. Only rows whose stored
  values really change are bumped — a no-op move and archived tasks (never
  renumbered) keep their previous `updated_at`. The temporary negative-position
  writes are transient (overwritten later in the same transaction) and are
  never stamped.
  """

  import Ecto.Query, warn: false

  alias Kanban.Columns
  alias Kanban.Columns.Column
  alias Kanban.Columns.Stage
  alias Kanban.Repo
  alias Kanban.Tasks.Broadcaster
  alias Kanban.Tasks.Goals
  alias Kanban.Tasks.History
  alias Kanban.Tasks.Queries
  alias Kanban.Tasks.Task

  require Logger

  @doc """
  Moves a task to a different column at a specific position.
  Respects WIP limit of target column.
  """
  def move_task(%Task{} = task, %Column{} = new_column, new_position) do
    old_column_id = task.column_id
    result = check_wip_and_perform_move(task, new_column, new_position, old_column_id)

    case result do
      {:ok, updated_task} ->
        Broadcaster.broadcast_task_change(updated_task, :task_moved)
        {:ok, updated_task}

      error ->
        error
    end
  end

  defp check_wip_and_perform_move(task, new_column, new_position, old_column_id) do
    cross_column? = new_column.id != old_column_id
    should_check_wip = cross_column? and task.type in [:work, :defect]

    if should_check_wip and wip_limit_exceeded?(new_column) do
      {:error, :wip_limit_reached}
    else
      perform_move(task, new_column, new_position, old_column_id)
    end
  end

  defp wip_limit_exceeded?(new_column) do
    current_count =
      Task
      |> where([t], t.column_id == ^new_column.id)
      |> where([t], t.type in [:work, :defect])
      |> where([t], is_nil(t.archived_at))
      |> Repo.aggregate(:count)

    new_column.wip_limit > 0 and current_count >= new_column.wip_limit
  end

  @doc """
  Reorders tasks within a column based on a list of task IDs.
  """
  def reorder_tasks(column, task_ids) do
    Repo.transaction(fn ->
      Repo.query!("SELECT pg_advisory_xact_lock($1)", [column.id])

      now = DateTime.utc_now(:second)
      old_positions = live_positions(column)

      # Move all LIVE tasks in the column to temp negative positions to avoid
      # unique constraint violations on the partial (column_id, position) index.
      # Archived tasks are excluded — they keep their stale positions and are
      # never renumbered (and the partial index ignores them anyway).
      Repo.query!(
        "UPDATE tasks SET position = -1 * id WHERE column_id = $1 AND position >= 0 AND archived_at IS NULL",
        [column.id]
      )

      # Only live tasks of this column are renumbered: an archived or foreign
      # id in the list neither moves nor consumes a position.
      live_ids = Enum.filter(task_ids, &Map.has_key?(old_positions, &1))

      assign_reorder_positions(column, live_ids, old_positions, now)
      assign_remaining_positions(column, length(live_ids), old_positions, now)
    end)

    :ok
  end

  defp live_positions(column) do
    Task
    |> where([t], t.column_id == ^column.id and is_nil(t.archived_at))
    |> select([t], {t.id, t.position})
    |> Repo.all()
    |> Map.new()
  end

  # Bumps updated_at only when the row's stored position really changes.
  defp position_set(id, new_position, old_positions, now) do
    if Map.get(old_positions, id) == new_position,
      do: [position: new_position],
      else: [position: new_position, updated_at: now]
  end

  defp assign_reorder_positions(column, task_ids, old_positions, now) do
    task_ids
    |> Enum.with_index()
    |> Enum.each(fn {task_id, index} ->
      Task
      |> where([t], t.id == ^task_id and t.column_id == ^column.id)
      |> where([t], is_nil(t.archived_at))
      |> Repo.update_all(set: position_set(task_id, index, old_positions, now))
    end)
  end

  defp assign_remaining_positions(column, offset, old_positions, now) do
    # Reassign positions to any remaining LIVE tasks still at temp positions
    # (live tasks in the column that were not included in task_ids). Archived
    # tasks were never moved to a temp position, so they are excluded here too.
    remaining_ids =
      Task
      |> where([t], t.column_id == ^column.id and t.position < 0)
      |> where([t], is_nil(t.archived_at))
      |> order_by([t], asc: t.id)
      |> select([t], t.id)
      |> Repo.all()

    remaining_ids
    |> Enum.with_index(offset)
    |> Enum.each(fn {id, pos} ->
      Task
      |> where([t], t.id == ^id)
      |> Repo.update_all(set: position_set(id, pos, old_positions, now))
    end)
  end

  @doc """
  Checks if a task can be added to a column (respects WIP limit).
  """
  def can_add_task?(%Column{} = column) do
    if column.wip_limit == 0 do
      true
    else
      current_count =
        Task
        |> where([t], t.column_id == ^column.id)
        |> where([t], t.type in [:work, :defect])
        |> where([t], is_nil(t.archived_at))
        |> Repo.aggregate(:count)

      current_count < column.wip_limit
    end
  end

  @doc """
  Gets the next position for a task in a column.

  WARNING: This function is not safe for concurrent use. If two callers
  read the same max position before either writes, both will get the same
  value, causing a unique constraint violation. Use `get_next_position_locked/1`
  inside a transaction for concurrent-safe position allocation.
  """
  def get_next_position(column) do
    compute_next_position(column.id)
  end

  @doc """
  Gets the next position for a task in a column with an advisory lock.

  Acquires a PostgreSQL transaction-level advisory lock on the column ID,
  serializing all position allocations for that column. This prevents
  duplicate position errors when concurrent operations target the same column.

  MUST be called within a `Repo.transaction` — the lock is released
  automatically when the transaction commits or rolls back.
  """
  def get_next_position_locked(column) do
    Repo.query!("SELECT pg_advisory_xact_lock($1)", [column.id])
    compute_next_position(column.id)
  end

  defp compute_next_position(column_id) do
    query =
      from t in Task,
        where: t.column_id == ^column_id,
        where: is_nil(t.archived_at),
        select: max(t.position)

    case Repo.one(query) do
      nil -> 0
      max_position -> max_position + 1
    end
  end

  @doc """
  Determines the status updates for a task moved into `column`, from the
  column's stage (see `Kanban.Columns.Stage`). A blocked task keeps its status.
  """
  def determine_status_for_column(column, task) do
    if task.status == :blocked do
      %{completed_at: nil}
    else
      column |> Stage.for_column() |> status_for_stage(task)
    end
  end

  defp status_for_stage(:not_started, _task), do: %{status: :open, completed_at: nil}
  defp status_for_stage(:in_progress, _task), do: %{status: :in_progress, completed_at: nil}

  defp status_for_stage(:done, task),
    do: %{status: :completed, completed_at: task.completed_at || DateTime.utc_now()}

  @doc """
  Reorders tasks after a task is deleted, decrementing positions.
  """
  def reorder_after_deletion(deleted_task) do
    query =
      from t in Task,
        where: t.column_id == ^deleted_task.column_id,
        where: t.position > ^deleted_task.position,
        where: is_nil(t.archived_at),
        order_by: t.position

    tasks = Repo.all(query)

    Enum.each(tasks, fn task ->
      Kanban.Tasks.update_task(task, %{position: task.position - 1})
    end)
  end

  defp perform_move(task, new_column, new_position, old_column_id) do
    Repo.transaction(fn ->
      # Lock columns in consistent order to prevent deadlocks
      [old_column_id, new_column.id]
      |> Enum.sort()
      |> Enum.each(fn col_id ->
        Repo.query!("SELECT pg_advisory_xact_lock($1)", [col_id])
      end)

      Logger.info(
        "perform_move: task_id=#{task.id}, old_column=#{old_column_id}, new_column=#{new_column.id}, new_position=#{new_position}, old_position=#{task.position}"
      )

      move_task_to_temp_position(task)

      now = DateTime.utc_now(:second)
      is_cross_column_move = new_column.id != old_column_id

      position =
        if is_cross_column_move do
          handle_cross_column_move(task, new_column, new_position, old_column_id, now)
        else
          insert_at_index(new_column, task, new_position, now)
        end

      updated_task = finalize_task_move(task, new_column, position, is_cross_column_move, now)

      if is_cross_column_move do
        old_column = Columns.get_column!(old_column_id)
        History.create_move_history(updated_task, old_column.name, new_column.name)

        Goals.update_parent_goal_position(updated_task, old_column_id, new_column.id, now)
      end

      updated_task
    end)
  end

  defp move_task_to_temp_position(task) do
    temp_position = -1 * task.id

    Task
    |> where([t], t.id == ^task.id)
    |> Repo.update_all(set: [position: temp_position])

    Logger.info("Task moved to temporary position #{temp_position}")
  end

  defp handle_cross_column_move(task, new_column, new_position, old_column_id, now) do
    old_column = Columns.get_column!(old_column_id)
    reorder_after_removal(old_column, task.position, now)
    insert_at_index(new_column, task, new_position, now)
  end

  # The board sends the index the card was dropped at among the column's other
  # cards, not a stored position. Positions can have gaps (archiving a task
  # does not renumber its column), and treating the index as a position then
  # put the card one or more places away from where it was dropped. So the
  # column's other live cards are laid out 0..n in their current order with the
  # moving card's slot at the index, and only rows whose position really
  # changes are written, and stamped (D357). Returns the moving card's position.
  defp insert_at_index(column, task, index, now) do
    others = other_live_positions(column, task.id)
    position = index |> max(0) |> min(length(others))
    {before, rest} = Enum.split(others, position)

    changed =
      (Enum.with_index(before) ++ Enum.with_index(rest, position + 1))
      |> Enum.reject(fn {{_id, old}, new} -> old == new end)

    write_positions(changed, now)
    position
  end

  # The column's live tasks other than `moving_task_id` (which sits at a
  # temporary negative position), as `{id, position}` in display order.
  defp other_live_positions(column, moving_task_id) do
    Task
    |> where([t], t.column_id == ^column.id and is_nil(t.archived_at))
    |> where([t], t.id != ^moving_task_id and t.position >= 0)
    |> order_by([t], asc: t.position, asc: t.id)
    |> select([t], {t.id, t.position})
    |> Repo.all()
  end

  # Parks the changed rows at temporary negative positions first so the partial
  # unique (column_id, position) index never sees a collision, then writes each
  # row's new position once.
  defp write_positions([], _now), do: :ok

  defp write_positions(changed, now) do
    ids = Enum.map(changed, fn {{id, _old}, _new} -> id end)

    from(t in Task, where: t.id in ^ids, update: [set: [position: fragment("-1 * ?", t.id)]])
    |> Repo.update_all([])

    Enum.each(changed, fn {{id, _old}, new} ->
      Task
      |> where([t], t.id == ^id)
      |> Repo.update_all(set: [position: new, updated_at: now])
    end)
  end

  defp finalize_task_move(task, new_column, new_position, cross_column?, now) do
    Logger.info(
      "Updating task #{task.id} to final position: column_id=#{new_column.id}, position=#{new_position}"
    )

    updates =
      %{column_id: new_column.id, position: new_position}
      |> Map.merge(determine_status_for_column(new_column, task))
      |> Map.merge(review_entry_updates(new_column.name, cross_column?))
      |> stamp_if_changed(task, now)

    Task
    |> where([t], t.id == ^task.id)
    |> Repo.update_all(set: Map.to_list(updates))

    Logger.info("Task updated successfully with status: #{inspect(updates[:status])}")

    updated_task = Queries.get_task!(task.id)
    Logger.info("Returning updated task: #{inspect(updated_task)}")

    updated_task
  end

  # A drag into Review from another column starts the task's review wait; a
  # reorder inside Review does not (see Kanban.Reviews.waiting_since/1).
  defp review_entry_updates("Review", true), do: %{review_requested_at: DateTime.utc_now(:second)}
  defp review_entry_updates(_column_name, _cross_column?), do: %{}

  # A same-column, same-position move rewrites the row with the values it
  # already holds; it must not look updated to an incremental sync.
  defp stamp_if_changed(updates, task, now) do
    if Enum.all?(updates, fn {field, value} -> Map.get(task, field) == value end),
      do: updates,
      else: Map.put(updates, :updated_at, now)
  end

  defp reorder_after_removal(column, removed_position, now) do
    query =
      from t in Task,
        where: t.column_id == ^column.id,
        where: t.position > ^removed_position,
        where: is_nil(t.archived_at),
        order_by: t.position

    tasks = Repo.all(query)

    Enum.each(tasks, fn task ->
      Task
      |> where([t], t.id == ^task.id)
      |> Repo.update_all(set: [position: task.position - 1, updated_at: now])
    end)
  end
end
