defmodule Kanban.RateLimiter do
  @moduledoc """
  Low-level Hammer rate-limit bucket store (ETS backend).

  This module only provides the raw `hit/3` / `hit/4` counters generated by
  `use Hammer`. The rate-limiting *policy* — which surfaces are limited, the
  thresholds, and how keys are built — lives in `Kanban.RateLimit`. Callers
  should always go through `Kanban.RateLimit`, never call this module directly.

  Started in the application supervision tree; the ETS table is in-memory and
  per-node, so counters reset on restart (acceptable for abuse throttling).
  """
  use Hammer, backend: :ets
end
