defmodule KanbanWeb.MetricsExcelExport do
  @moduledoc """
  Generates Excel (.xlsx) exports for metrics data.
  Supports both AI-optimized and regular board types with appropriate columns/labels.
  """

  use Gettext, backend: KanbanWeb.Gettext

  alias Elixlsx.Sheet
  alias Elixlsx.Workbook
  alias KanbanWeb.MetricsLive.Helpers

  @col_widths_base %{1 => 12, 2 => 40, 3 => 22, 4 => 22, 5 => 22, 6 => 20}
  @bold [bold: true]

  def generate(board, metric, opts, data) do
    sheet = build_sheet(board, metric, opts, data)
    workbook = %Workbook{sheets: [sheet]}

    case Elixlsx.write_to_memory(workbook, "export.xlsx") do
      {:ok, {_filename, binary}} -> {:ok, binary}
      {:error, reason} -> {:error, reason}
    end
  end

  # Sheet names are translated. Every one reuses a msgid the metrics dashboard
  # already ships, whose longest existing translation is well inside the
  # 31-character sheet-name cap a spreadsheet enforces, so translation cannot
  # produce a name the writer rejects.
  defp build_sheet(board, "throughput", opts, data) do
    header = header_rows(board, gettext("Throughput"), opts)
    {task_headers, task_rows} = throughput_task_rows(board, data)
    {goal_headers, goal_rows} = throughput_goal_rows(board, data)

    rows =
      header ++
        [task_headers | task_rows] ++
        [[]] ++
        [goal_headers | goal_rows]

    %Sheet{name: gettext("Throughput"), rows: rows, col_widths: @col_widths_base}
  end

  defp build_sheet(board, "cycle-time", opts, data) do
    header = header_rows(board, gettext("Cycle Time"), opts)
    {col_headers, data_rows} = cycle_time_rows(board, data)
    rows = header ++ [col_headers | data_rows]
    %Sheet{name: gettext("Cycle Time"), rows: rows, col_widths: @col_widths_base}
  end

  defp build_sheet(board, "lead-time", opts, data) do
    header = header_rows(board, gettext("Lead Time"), opts)
    {col_headers, data_rows} = lead_time_rows(board, data)
    rows = header ++ [col_headers | data_rows]
    %Sheet{name: gettext("Lead Time"), rows: rows, col_widths: @col_widths_base}
  end

  defp build_sheet(board, "wait-time", opts, data) do
    header = header_rows(board, gettext("Wait Time"), opts)
    review_section = wait_time_review_section(board, data)
    {backlog_headers, backlog_rows} = backlog_wait_rows(board, data)

    backlog_label =
      if ai_optimized?(board), do: gettext("Claimed Tasks"), else: gettext("Started Tasks")

    rows =
      header ++
        review_section ++
        [[[backlog_label | @bold]]] ++
        [backlog_headers | backlog_rows]

    %Sheet{name: gettext("Wait Time"), rows: rows, col_widths: @col_widths_base}
  end

  defp build_sheet(board, _metric, opts, _data) do
    rows = header_rows(board, gettext("Unknown"), opts)
    %Sheet{name: gettext("Export"), rows: rows, col_widths: @col_widths_base}
  end

  defp wait_time_review_section(board, data) do
    if ai_optimized?(board) do
      {review_headers, review_rows} = review_wait_rows(board, data)
      [[[gettext("Reviewed Tasks") | @bold]]] ++ [review_headers | review_rows] ++ [[]]
    else
      []
    end
  end

  # Header rows (rows 1-4)

  # Each label is one whole interpolated phrase rather than a translated word
  # glued to a value, so a translator receives the entire sentence and can
  # reorder it for their locale.
  defp header_rows(board, metric_label, opts) do
    time_range_label = format_time_range(opts[:time_range])

    weekends_label =
      if opts[:exclude_weekends], do: gettext("Excluded"), else: gettext("Included")

    generated_at = Calendar.strftime(DateTime.utc_now(), "%b %d, %Y %I:%M %p")

    # safe_text still wraps the whole cell, since the board name interpolated
    # into it is user-controlled.
    title =
      safe_text(gettext("%{metric} Metrics — %{board}", metric: metric_label, board: board.name))

    row1 = [[title | @bold]]
    row2 = [filter_summary(board, opts, time_range_label, weekends_label)]
    row3 = [gettext("Generated by Stride | %{timestamp}", timestamp: generated_at)]

    [row1, row2, row3, []]
  end

  defp filter_summary(board, opts, time_range_label, weekends_label) do
    parts = [
      gettext("Time Range: %{value}", value: time_range_label),
      gettext("Weekends: %{value}", value: weekends_label)
    ]

    parts =
      if ai_optimized?(board) do
        agent_label = safe_text(opts[:agent_name] || gettext("All Agents"))
        parts ++ [gettext("Agent: %{value}", value: agent_label)]
      else
        parts
      end

    Enum.join(parts, " | ")
  end

  # The column headers shared by the two throughput sections and reused as the
  # leading columns elsewhere.
  defp identifier_and_title_headers do
    [gettext("Identifier"), gettext("Title")]
  end

  defp agent_header(board) do
    if ai_optimized?(board), do: [gettext("Agent")], else: []
  end

  # Throughput rows

  defp throughput_task_rows(board, data) do
    tasks = Map.get(data, :tasks, [])

    headers =
      if ai_optimized?(board) do
        bold_row(
          identifier_and_title_headers() ++
            [gettext("Created"), gettext("Claimed"), gettext("Completed"), gettext("Agent")]
        )
      else
        bold_row(identifier_and_title_headers() ++ [gettext("Created"), gettext("Completed")])
      end

    rows = Enum.map(tasks, &throughput_task_row(&1, ai_optimized?(board)))

    {headers, rows}
  end

  defp throughput_task_row(task, ai_optimized) do
    base = [
      safe_text(task[:identifier]),
      safe_text(task[:title]),
      format_datetime_cell(task[:inserted_at])
    ]

    if ai_optimized do
      base ++
        [
          format_datetime_cell(task[:claimed_at]),
          format_datetime_cell(task[:completed_at]),
          safe_text(task[:completed_by_agent] || "—")
        ]
    else
      base ++ [format_datetime_cell(task[:completed_at])]
    end
  end

  defp throughput_goal_rows(board, data) do
    goals = Map.get(data, :completed_goals, [])

    headers =
      bold_row(
        identifier_and_title_headers() ++
          [gettext("Created"), gettext("Completed")] ++ agent_header(board)
      )

    rows = Enum.map(goals, &throughput_goal_row(&1, ai_optimized?(board)))

    {headers, rows}
  end

  defp throughput_goal_row(goal, ai_optimized) do
    base = [
      safe_text(goal[:identifier]),
      safe_text(goal[:title]),
      format_datetime_cell(goal[:inserted_at]),
      format_datetime_cell(goal[:completed_at])
    ]

    if ai_optimized, do: base ++ [safe_text(goal[:completed_by_agent] || "—")], else: base
  end

  # Cycle Time rows

  defp cycle_time_rows(board, data) do
    tasks = Map.get(data, :tasks, [])
    claimed_label = if ai_optimized?(board), do: gettext("Claimed"), else: gettext("Started")

    headers =
      bold_row(
        identifier_and_title_headers() ++
          [gettext("Cycle Time"), claimed_label, gettext("Completed")] ++ agent_header(board)
      )

    rows = Enum.map(tasks, &cycle_time_row(&1, ai_optimized?(board)))

    {headers, rows}
  end

  defp cycle_time_row(task, ai_optimized) do
    base = [
      safe_text(task[:identifier]),
      safe_text(task[:title]),
      format_time_cell(task[:cycle_time_seconds]),
      format_datetime_cell(task[:claimed_at]),
      format_datetime_cell(task[:completed_at])
    ]

    if ai_optimized do
      base ++ [safe_text(task[:completed_by_agent] || "—")]
    else
      base
    end
  end

  # Lead Time rows

  defp lead_time_rows(board, data) do
    tasks = Map.get(data, :tasks, [])

    headers =
      bold_row(
        identifier_and_title_headers() ++
          [gettext("Lead Time"), gettext("Created"), gettext("Completed")] ++
          agent_header(board)
      )

    rows = Enum.map(tasks, &lead_time_row(&1, ai_optimized?(board)))

    {headers, rows}
  end

  defp lead_time_row(task, ai_optimized) do
    base = [
      safe_text(task[:identifier]),
      safe_text(task[:title]),
      format_time_cell(task[:lead_time_seconds]),
      format_datetime_cell(task[:inserted_at]),
      format_datetime_cell(task[:completed_at])
    ]

    if ai_optimized do
      base ++ [safe_text(task[:completed_by_agent] || "—")]
    else
      base
    end
  end

  # Wait Time rows

  defp review_wait_rows(_board, data) do
    tasks =
      data
      |> Map.get(:grouped_review_tasks, [])
      |> Enum.flat_map(fn {_date, tasks} -> tasks end)

    headers =
      bold_row(
        identifier_and_title_headers() ++
          [
            gettext("Review Wait"),
            gettext("Completed"),
            gettext("Reviewed"),
            gettext("Agent")
          ]
      )

    rows = Enum.map(tasks, &review_wait_row/1)

    {headers, rows}
  end

  defp review_wait_row(task) do
    [
      safe_text(task[:identifier]),
      safe_text(task[:title]),
      format_time_cell(task[:review_wait_seconds]),
      format_datetime_cell(task[:completed_at]),
      format_datetime_cell(task[:reviewed_at]),
      safe_text(task[:completed_by_agent] || "—")
    ]
  end

  defp backlog_wait_rows(board, data) do
    tasks =
      data
      |> Map.get(:grouped_backlog_tasks, [])
      |> Enum.flat_map(fn {_date, tasks} -> tasks end)

    headers = backlog_wait_headers(board)
    rows = Enum.map(tasks, &backlog_wait_row(&1, ai_optimized?(board)))

    {headers, rows}
  end

  defp backlog_wait_headers(board) do
    wait_label = if ai_optimized?(board), do: gettext("Backlog Wait"), else: gettext("Queue Wait")
    claimed_label = if ai_optimized?(board), do: gettext("Claimed"), else: gettext("Started")

    bold_row(
      identifier_and_title_headers() ++
        [wait_label, gettext("Created"), claimed_label] ++ agent_header(board)
    )
  end

  defp backlog_wait_row(task, ai_optimized) do
    base = [
      safe_text(task[:identifier]),
      safe_text(task[:title]),
      format_time_cell(task[:backlog_wait_seconds]),
      format_datetime_cell(task[:inserted_at]),
      format_datetime_cell(task[:claimed_at])
    ]

    if ai_optimized do
      base ++ [safe_text(task[:completed_by_agent] || "—")]
    else
      base
    end
  end

  # Helpers

  defp ai_optimized?(board), do: board.ai_optimized_board

  defp bold_row(cells), do: Enum.map(cells, fn cell -> [cell | @bold] end)

  # Prefix any string that Excel/LibreOffice would interpret as a formula with a
  # single apostrophe so it renders as literal text. Applied to every cell whose
  # value originates from user-controlled fields (task title, identifier,
  # completed_by_agent, board.name, agent name filter). Non-strings pass through
  # untouched so date/duration cell builders are not affected.
  defp safe_text(<<c, _::binary>> = s) when c in [?=, ?+, ?-, ?@, 0x09, 0x0D],
    do: "'" <> s

  defp safe_text(s), do: s

  defp format_datetime_cell(nil), do: gettext("N/A")
  defp format_datetime_cell(datetime), do: Helpers.format_datetime(datetime)

  defp format_time_cell(nil), do: gettext("N/A")
  defp format_time_cell(seconds), do: Helpers.format_time(seconds)

  # Shares the five range labels with KanbanWeb.MetricsPdfHTML through Helpers
  # so the two cannot drift. The fallback stays local and unchanged: this module
  # has always treated an unrecognized range as the 30-day label, where the PDF
  # reads "Custom Range". Unifying that is a behavior change, not a translation.
  defp format_time_range(range) do
    Helpers.time_range_label(range) || gettext("Last 30 Days")
  end
end
