defmodule KanbanWeb.MetricsPdfHTML do
  use KanbanWeb, :html

  embed_templates "metrics_pdf_html/*"

  def shared_pdf_css do
    """
    @page {
      size: letter;
      margin: 0.75in 0.75in 1in 0.75in;
      @bottom-center {
        content: "Generated by Stride";
        font-size: 7pt;
        color: #9ca3af;
        font-family: 'Helvetica Neue', Arial, sans-serif;
      }
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; line-height: 1.4; color: #1f2937; }
    .header { padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 24pt; font-weight: bold; color: #1f2937; margin-bottom: 8px; }
    .header .subtitle { font-size: 12pt; color: #6b7280; }
    .meta { display: flex; justify-content: space-between; background-color: #f3f4f6; padding: 12px; border-radius: 6px; margin-bottom: 24px; font-size: 9pt; }
    .meta-label { font-weight: 600; color: #4b5563; }
    .meta-value { color: #1f2937; }
    .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }
    .stat-card { background-color: #ffffff; border: 2px solid #e5e7eb; border-radius: 8px; padding: 12px; }
    .stat-card-blue { border-left: 4px solid #3b82f6; }
    .stat-card-purple { border-left: 4px solid #a855f7; }
    .stat-card-green { border-left: 4px solid #22c55e; }
    .stat-card-red { border-left: 4px solid #ef4444; }
    .stat-card-amber { border-left: 4px solid #f59e0b; }
    .stat-header { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }
    .stat-icon { width: 32px; height: 32px; border-radius: 6px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    .stat-icon svg { width: 20px; height: 20px; }
    .stat-icon-blue { background-color: #dbeafe; }
    .stat-icon-purple { background-color: #f3e8ff; }
    .stat-icon-green { background-color: #dcfce7; }
    .stat-icon-red { background-color: #fee2e2; }
    .stat-icon-amber { background-color: #fef3c7; }
    .stat-label { font-size: 9pt; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }
    .stat-value { font-size: 20pt; font-weight: bold; color: #1f2937; text-align: center; }
    .section-title { font-size: 14pt; font-weight: bold; color: #1f2937; margin-top: 24px; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid #e5e7eb; }
    .task-group { margin-bottom: 16px; }
    .task-group-date { font-size: 10pt; font-weight: bold; color: #1f2937; }
    .task-item { background-color: #f9fafb; border: 1px solid #e5e7eb; padding: 8px 12px; margin-bottom: 6px; margin-left: 12px; border-radius: 4px; page-break-inside: avoid; }
    .task-header { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }
    .task-identifier { background-color: #3b82f6; color: white; padding: 2px 8px; border-radius: 4px; font-size: 8pt; font-weight: bold; }
    .task-title { font-size: 9pt; font-weight: 600; color: #1f2937; flex: 1; }
    .task-meta { font-size: 7pt; color: #9ca3af; margin-top: 4px; display: flex; gap: 12px; }
    .no-data { text-align: center; padding: 48px 24px; color: #6b7280; font-size: 12pt; }
    """
  end

  defp format_date(nil), do: "N/A"

  defp format_date(date) do
    Calendar.strftime(date, "%b %d, %Y")
  end

  defp format_datetime(nil), do: "N/A"

  defp format_datetime(datetime) do
    Calendar.strftime(datetime, "%b %d, %Y %I:%M %p")
  end

  defp format_time(seconds) do
    KanbanWeb.MetricsLive.Helpers.format_time(seconds)
  end

  defp format_time_range(:today), do: "Today"
  defp format_time_range(:last_7_days), do: "Last 7 Days"
  defp format_time_range(:last_30_days), do: "Last 30 Days"
  defp format_time_range(:last_90_days), do: "Last 90 Days"
  defp format_time_range(:all_time), do: "All Time"
  defp format_time_range(_), do: "Custom Range"

  defp agent_filter_label(nil), do: "All Agents"
  defp agent_filter_label(name), do: name

  defp weekend_filter_label(true), do: "Weekends Excluded"
  defp weekend_filter_label(false), do: "Weekends Included"

  defp calculate_bar_width(_count, nil), do: 0
  defp calculate_bar_width(_count, peak) when peak == 0, do: 0

  defp calculate_bar_width(count, peak) when peak > 0 do
    Float.round(count / peak * 100, 1)
  end

  defp format_short_date(date) do
    Calendar.strftime(date, "%b %d")
  end

  defp line_chart_points(daily_times, chart_width, chart_height, max_val) when max_val > 0 do
    count = length(daily_times)
    padding = 0

    daily_times
    |> Enum.with_index()
    |> Enum.map(fn {day, i} ->
      x =
        if count > 1,
          do: padding + i / (count - 1) * (chart_width - 2 * padding),
          else: chart_width / 2

      y = chart_height - day.average_hours / max_val * chart_height
      {Float.round(x * 1.0, 1), Float.round(y * 1.0, 1)}
    end)
  end

  defp line_chart_points(_daily_times, chart_width, chart_height, _max_val) do
    [{Float.round(chart_width / 2.0, 1), Float.round(chart_height / 2.0, 1)}]
  end

  defp points_to_polyline(points) do
    Enum.map_join(points, " ", fn {x, y} -> "#{x},#{y}" end)
  end

  defp line_chart_y_labels(max_val, count) when max_val > 0 do
    Enum.map(0..(count - 1), fn i ->
      Float.round(max_val * i / (count - 1), 1)
    end)
  end

  defp line_chart_y_labels(_max_val, _count), do: [0.0]
end
